export let products = [
    {
        id: 1,
        title: "EcoBoligráfo",
        price: 121,
        description: "Trazo fino y de color negro",
        imageUrl: "https://res.cloudinary.com/dmlqg9nvh/image/upload/v1707738046/Mariela/membresia-rediseniarte/ELEMENTOS%20GRAFICOS/icon-carita-feliz_m2io5a.svg",
        stock: 12,
        category: "ecologicas",
    },
    {
        id: 2,
        title: "Boligráfo Metálico retractil",
        price: 230,
        description: "Metático de trazo fino y de color negro",
        imageUrl: "https://res.cloudinary.com/dmlqg9nvh/image/upload/v1707738047/Mariela/membresia-rediseniarte/ELEMENTOS%20GRAFICOS/Taza-con-corazon_sqcyok.png",
        stock: 5,
        category: "metalicos",
    },
    {
        id: 3,
        title: "Boligráfo Metalico fijo",
        price: 209,
        description: "Trazo mediano y de color azul",
        imageUrl: "https://res.cloudinary.com/dmlqg9nvh/image/upload/v1707738047/Mariela/membresia-rediseniarte/ELEMENTOS%20GRAFICOS/planta-decorativa_dlhsey.png",
        stock: 7,
        category: "metalicos",
    },
    {
        id: 4,
        title: "EcoBoligráfo retractil",
        price: 130,
        description: "Ecológico de trazo fino, retractil y de color negro",
        imageUrl: "https://res.cloudinary.com/dmlqg9nvh/image/upload/v1707738047/Mariela/membresia-rediseniarte/ELEMENTOS%20GRAFICOS/globo-dialogo-con-corazon_lcdgxu.png",
        stock: 15,
        category: "ecologicas",
    },
]